#!/bin/bash

scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.114:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.98:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.152:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.136:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.128:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.157:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.121:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.89:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.163:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.83:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.84:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.123:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.82:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.81:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.68:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.167:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.88:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.87:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.120:/Library/Preferences/Xsan/automount.plist
scp /Users/charley/Desktop/edit/automount.plist sysadmin@10.30.20.122:/Library/Preferences/Xsan/automount.plist
